language: node_js
node_js:
  -15.12.0
cache: yarn

install:
  - yarn install

script:
  - yarn start
  - yarn run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: travis